// Code generated by go-swagger; DO NOT EDIT.

package workflow_user_interaction_presentation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteWorkflowUserInteractionPresentationExecutionParams creates a new DeleteWorkflowUserInteractionPresentationExecutionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteWorkflowUserInteractionPresentationExecutionParams() *DeleteWorkflowUserInteractionPresentationExecutionParams {
	return &DeleteWorkflowUserInteractionPresentationExecutionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWorkflowUserInteractionPresentationExecutionParamsWithTimeout creates a new DeleteWorkflowUserInteractionPresentationExecutionParams object
// with the ability to set a timeout on a request.
func NewDeleteWorkflowUserInteractionPresentationExecutionParamsWithTimeout(timeout time.Duration) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	return &DeleteWorkflowUserInteractionPresentationExecutionParams{
		timeout: timeout,
	}
}

// NewDeleteWorkflowUserInteractionPresentationExecutionParamsWithContext creates a new DeleteWorkflowUserInteractionPresentationExecutionParams object
// with the ability to set a context for a request.
func NewDeleteWorkflowUserInteractionPresentationExecutionParamsWithContext(ctx context.Context) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	return &DeleteWorkflowUserInteractionPresentationExecutionParams{
		Context: ctx,
	}
}

// NewDeleteWorkflowUserInteractionPresentationExecutionParamsWithHTTPClient creates a new DeleteWorkflowUserInteractionPresentationExecutionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteWorkflowUserInteractionPresentationExecutionParamsWithHTTPClient(client *http.Client) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	return &DeleteWorkflowUserInteractionPresentationExecutionParams{
		HTTPClient: client,
	}
}

/*
DeleteWorkflowUserInteractionPresentationExecutionParams contains all the parameters to send to the API endpoint

	for the delete workflow user interaction presentation execution operation.

	Typically these are written to a http.Request.
*/
type DeleteWorkflowUserInteractionPresentationExecutionParams struct {

	// ExecutionID.
	ExecutionID string

	// PresentationExecutionID.
	PresentationExecutionID string

	// WorkflowID.
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete workflow user interaction presentation execution params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithDefaults() *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete workflow user interaction presentation execution params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithTimeout(timeout time.Duration) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithContext(ctx context.Context) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithHTTPClient(client *http.Client) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExecutionID adds the executionID to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithExecutionID(executionID string) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetExecutionID(executionID)
	return o
}

// SetExecutionID adds the executionId to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetExecutionID(executionID string) {
	o.ExecutionID = executionID
}

// WithPresentationExecutionID adds the presentationExecutionID to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithPresentationExecutionID(presentationExecutionID string) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetPresentationExecutionID(presentationExecutionID)
	return o
}

// SetPresentationExecutionID adds the presentationExecutionId to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetPresentationExecutionID(presentationExecutionID string) {
	o.PresentationExecutionID = presentationExecutionID
}

// WithWorkflowID adds the workflowID to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WithWorkflowID(workflowID string) *DeleteWorkflowUserInteractionPresentationExecutionParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the delete workflow user interaction presentation execution params
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWorkflowUserInteractionPresentationExecutionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param executionId
	if err := r.SetPathParam("executionId", o.ExecutionID); err != nil {
		return err
	}

	// path param presentationExecutionId
	if err := r.SetPathParam("presentationExecutionId", o.PresentationExecutionID); err != nil {
		return err
	}

	// path param workflowId
	if err := r.SetPathParam("workflowId", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
