// Code generated by go-swagger; DO NOT EDIT.

package workflow_run_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AnswerUserInteractionReader is a Reader for the AnswerUserInteraction structure.
type AnswerUserInteractionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AnswerUserInteractionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAnswerUserInteractionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAnswerUserInteractionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAnswerUserInteractionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAnswerUserInteractionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /workflows/{workflowId}/executions/{executionId}/interaction] answerUserInteraction", response, response.Code())
	}
}

// NewAnswerUserInteractionNoContent creates a AnswerUserInteractionNoContent with default headers values
func NewAnswerUserInteractionNoContent() *AnswerUserInteractionNoContent {
	return &AnswerUserInteractionNoContent{}
}

/*
AnswerUserInteractionNoContent describes a response with status code 204, with default header values.

No content
*/
type AnswerUserInteractionNoContent struct {
}

// IsSuccess returns true when this answer user interaction no content response has a 2xx status code
func (o *AnswerUserInteractionNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this answer user interaction no content response has a 3xx status code
func (o *AnswerUserInteractionNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this answer user interaction no content response has a 4xx status code
func (o *AnswerUserInteractionNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this answer user interaction no content response has a 5xx status code
func (o *AnswerUserInteractionNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this answer user interaction no content response a status code equal to that given
func (o *AnswerUserInteractionNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the answer user interaction no content response
func (o *AnswerUserInteractionNoContent) Code() int {
	return 204
}

func (o *AnswerUserInteractionNoContent) Error() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionNoContent ", 204)
}

func (o *AnswerUserInteractionNoContent) String() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionNoContent ", 204)
}

func (o *AnswerUserInteractionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAnswerUserInteractionBadRequest creates a AnswerUserInteractionBadRequest with default headers values
func NewAnswerUserInteractionBadRequest() *AnswerUserInteractionBadRequest {
	return &AnswerUserInteractionBadRequest{}
}

/*
AnswerUserInteractionBadRequest describes a response with status code 400, with default header values.

The request is invalid(validation error)
*/
type AnswerUserInteractionBadRequest struct {
}

// IsSuccess returns true when this answer user interaction bad request response has a 2xx status code
func (o *AnswerUserInteractionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this answer user interaction bad request response has a 3xx status code
func (o *AnswerUserInteractionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this answer user interaction bad request response has a 4xx status code
func (o *AnswerUserInteractionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this answer user interaction bad request response has a 5xx status code
func (o *AnswerUserInteractionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this answer user interaction bad request response a status code equal to that given
func (o *AnswerUserInteractionBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the answer user interaction bad request response
func (o *AnswerUserInteractionBadRequest) Code() int {
	return 400
}

func (o *AnswerUserInteractionBadRequest) Error() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionBadRequest ", 400)
}

func (o *AnswerUserInteractionBadRequest) String() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionBadRequest ", 400)
}

func (o *AnswerUserInteractionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAnswerUserInteractionUnauthorized creates a AnswerUserInteractionUnauthorized with default headers values
func NewAnswerUserInteractionUnauthorized() *AnswerUserInteractionUnauthorized {
	return &AnswerUserInteractionUnauthorized{}
}

/*
AnswerUserInteractionUnauthorized describes a response with status code 401, with default header values.

The user is not authorized
*/
type AnswerUserInteractionUnauthorized struct {
}

// IsSuccess returns true when this answer user interaction unauthorized response has a 2xx status code
func (o *AnswerUserInteractionUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this answer user interaction unauthorized response has a 3xx status code
func (o *AnswerUserInteractionUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this answer user interaction unauthorized response has a 4xx status code
func (o *AnswerUserInteractionUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this answer user interaction unauthorized response has a 5xx status code
func (o *AnswerUserInteractionUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this answer user interaction unauthorized response a status code equal to that given
func (o *AnswerUserInteractionUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the answer user interaction unauthorized response
func (o *AnswerUserInteractionUnauthorized) Code() int {
	return 401
}

func (o *AnswerUserInteractionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionUnauthorized ", 401)
}

func (o *AnswerUserInteractionUnauthorized) String() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionUnauthorized ", 401)
}

func (o *AnswerUserInteractionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAnswerUserInteractionNotFound creates a AnswerUserInteractionNotFound with default headers values
func NewAnswerUserInteractionNotFound() *AnswerUserInteractionNotFound {
	return &AnswerUserInteractionNotFound{}
}

/*
AnswerUserInteractionNotFound describes a response with status code 404, with default header values.

Can not find a workflow with the specified ID or the user does not have 'read' access rights for that workflow
*/
type AnswerUserInteractionNotFound struct {
}

// IsSuccess returns true when this answer user interaction not found response has a 2xx status code
func (o *AnswerUserInteractionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this answer user interaction not found response has a 3xx status code
func (o *AnswerUserInteractionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this answer user interaction not found response has a 4xx status code
func (o *AnswerUserInteractionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this answer user interaction not found response has a 5xx status code
func (o *AnswerUserInteractionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this answer user interaction not found response a status code equal to that given
func (o *AnswerUserInteractionNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the answer user interaction not found response
func (o *AnswerUserInteractionNotFound) Code() int {
	return 404
}

func (o *AnswerUserInteractionNotFound) Error() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionNotFound ", 404)
}

func (o *AnswerUserInteractionNotFound) String() string {
	return fmt.Sprintf("[POST /workflows/{workflowId}/executions/{executionId}/interaction][%d] answerUserInteractionNotFound ", 404)
}

func (o *AnswerUserInteractionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
