// Code generated by go-swagger; DO NOT EDIT.

package task_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPermissionsForTaskParams creates a new GetPermissionsForTaskParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPermissionsForTaskParams() *GetPermissionsForTaskParams {
	return &GetPermissionsForTaskParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPermissionsForTaskParamsWithTimeout creates a new GetPermissionsForTaskParams object
// with the ability to set a timeout on a request.
func NewGetPermissionsForTaskParamsWithTimeout(timeout time.Duration) *GetPermissionsForTaskParams {
	return &GetPermissionsForTaskParams{
		timeout: timeout,
	}
}

// NewGetPermissionsForTaskParamsWithContext creates a new GetPermissionsForTaskParams object
// with the ability to set a context for a request.
func NewGetPermissionsForTaskParamsWithContext(ctx context.Context) *GetPermissionsForTaskParams {
	return &GetPermissionsForTaskParams{
		Context: ctx,
	}
}

// NewGetPermissionsForTaskParamsWithHTTPClient creates a new GetPermissionsForTaskParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPermissionsForTaskParamsWithHTTPClient(client *http.Client) *GetPermissionsForTaskParams {
	return &GetPermissionsForTaskParams{
		HTTPClient: client,
	}
}

/*
GetPermissionsForTaskParams contains all the parameters to send to the API endpoint

	for the get permissions for task operation.

	Typically these are written to a http.Request.
*/
type GetPermissionsForTaskParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get permissions for task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsForTaskParams) WithDefaults() *GetPermissionsForTaskParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get permissions for task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsForTaskParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get permissions for task params
func (o *GetPermissionsForTaskParams) WithTimeout(timeout time.Duration) *GetPermissionsForTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get permissions for task params
func (o *GetPermissionsForTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get permissions for task params
func (o *GetPermissionsForTaskParams) WithContext(ctx context.Context) *GetPermissionsForTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get permissions for task params
func (o *GetPermissionsForTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get permissions for task params
func (o *GetPermissionsForTaskParams) WithHTTPClient(client *http.Client) *GetPermissionsForTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get permissions for task params
func (o *GetPermissionsForTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get permissions for task params
func (o *GetPermissionsForTaskParams) WithID(id string) *GetPermissionsForTaskParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get permissions for task params
func (o *GetPermissionsForTaskParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPermissionsForTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
