// Code generated by go-swagger; DO NOT EDIT.

package task_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// UpdateTaskReader is a Reader for the UpdateTask structure.
type UpdateTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateTaskBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateTaskUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateTaskNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /tasks/{id}] updateTask", response, response.Code())
	}
}

// NewUpdateTaskOK creates a UpdateTaskOK with default headers values
func NewUpdateTaskOK() *UpdateTaskOK {
	return &UpdateTaskOK{}
}

/*
UpdateTaskOK describes a response with status code 200, with default header values.

The request is successful
*/
type UpdateTaskOK struct {
	Payload *models.Task
}

// IsSuccess returns true when this update task o k response has a 2xx status code
func (o *UpdateTaskOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update task o k response has a 3xx status code
func (o *UpdateTaskOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update task o k response has a 4xx status code
func (o *UpdateTaskOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update task o k response has a 5xx status code
func (o *UpdateTaskOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update task o k response a status code equal to that given
func (o *UpdateTaskOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update task o k response
func (o *UpdateTaskOK) Code() int {
	return 200
}

func (o *UpdateTaskOK) Error() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskOK  %+v", 200, o.Payload)
}

func (o *UpdateTaskOK) String() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskOK  %+v", 200, o.Payload)
}

func (o *UpdateTaskOK) GetPayload() *models.Task {
	return o.Payload
}

func (o *UpdateTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTaskBadRequest creates a UpdateTaskBadRequest with default headers values
func NewUpdateTaskBadRequest() *UpdateTaskBadRequest {
	return &UpdateTaskBadRequest{}
}

/*
UpdateTaskBadRequest describes a response with status code 400, with default header values.

The request is invalid(validation error)
*/
type UpdateTaskBadRequest struct {
}

// IsSuccess returns true when this update task bad request response has a 2xx status code
func (o *UpdateTaskBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update task bad request response has a 3xx status code
func (o *UpdateTaskBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update task bad request response has a 4xx status code
func (o *UpdateTaskBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update task bad request response has a 5xx status code
func (o *UpdateTaskBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update task bad request response a status code equal to that given
func (o *UpdateTaskBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update task bad request response
func (o *UpdateTaskBadRequest) Code() int {
	return 400
}

func (o *UpdateTaskBadRequest) Error() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskBadRequest ", 400)
}

func (o *UpdateTaskBadRequest) String() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskBadRequest ", 400)
}

func (o *UpdateTaskBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTaskUnauthorized creates a UpdateTaskUnauthorized with default headers values
func NewUpdateTaskUnauthorized() *UpdateTaskUnauthorized {
	return &UpdateTaskUnauthorized{}
}

/*
UpdateTaskUnauthorized describes a response with status code 401, with default header values.

The user is not authorized
*/
type UpdateTaskUnauthorized struct {
}

// IsSuccess returns true when this update task unauthorized response has a 2xx status code
func (o *UpdateTaskUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update task unauthorized response has a 3xx status code
func (o *UpdateTaskUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update task unauthorized response has a 4xx status code
func (o *UpdateTaskUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update task unauthorized response has a 5xx status code
func (o *UpdateTaskUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update task unauthorized response a status code equal to that given
func (o *UpdateTaskUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update task unauthorized response
func (o *UpdateTaskUnauthorized) Code() int {
	return 401
}

func (o *UpdateTaskUnauthorized) Error() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskUnauthorized ", 401)
}

func (o *UpdateTaskUnauthorized) String() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskUnauthorized ", 401)
}

func (o *UpdateTaskUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTaskNotFound creates a UpdateTaskNotFound with default headers values
func NewUpdateTaskNotFound() *UpdateTaskNotFound {
	return &UpdateTaskNotFound{}
}

/*
UpdateTaskNotFound describes a response with status code 404, with default header values.

Can not find a task with the specified ID or the user does not have 'read' access rights for that workflow
*/
type UpdateTaskNotFound struct {
}

// IsSuccess returns true when this update task not found response has a 2xx status code
func (o *UpdateTaskNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update task not found response has a 3xx status code
func (o *UpdateTaskNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update task not found response has a 4xx status code
func (o *UpdateTaskNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update task not found response has a 5xx status code
func (o *UpdateTaskNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update task not found response a status code equal to that given
func (o *UpdateTaskNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update task not found response
func (o *UpdateTaskNotFound) Code() int {
	return 404
}

func (o *UpdateTaskNotFound) Error() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskNotFound ", 404)
}

func (o *UpdateTaskNotFound) String() string {
	return fmt.Sprintf("[POST /tasks/{id}][%d] updateTaskNotFound ", 404)
}

func (o *UpdateTaskNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
