// Code generated by go-swagger; DO NOT EDIT.

package actions_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPermissionsForActionParams creates a new GetPermissionsForActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPermissionsForActionParams() *GetPermissionsForActionParams {
	return &GetPermissionsForActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPermissionsForActionParamsWithTimeout creates a new GetPermissionsForActionParams object
// with the ability to set a timeout on a request.
func NewGetPermissionsForActionParamsWithTimeout(timeout time.Duration) *GetPermissionsForActionParams {
	return &GetPermissionsForActionParams{
		timeout: timeout,
	}
}

// NewGetPermissionsForActionParamsWithContext creates a new GetPermissionsForActionParams object
// with the ability to set a context for a request.
func NewGetPermissionsForActionParamsWithContext(ctx context.Context) *GetPermissionsForActionParams {
	return &GetPermissionsForActionParams{
		Context: ctx,
	}
}

// NewGetPermissionsForActionParamsWithHTTPClient creates a new GetPermissionsForActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPermissionsForActionParamsWithHTTPClient(client *http.Client) *GetPermissionsForActionParams {
	return &GetPermissionsForActionParams{
		HTTPClient: client,
	}
}

/*
GetPermissionsForActionParams contains all the parameters to send to the API endpoint

	for the get permissions for action operation.

	Typically these are written to a http.Request.
*/
type GetPermissionsForActionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get permissions for action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsForActionParams) WithDefaults() *GetPermissionsForActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get permissions for action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsForActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get permissions for action params
func (o *GetPermissionsForActionParams) WithTimeout(timeout time.Duration) *GetPermissionsForActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get permissions for action params
func (o *GetPermissionsForActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get permissions for action params
func (o *GetPermissionsForActionParams) WithContext(ctx context.Context) *GetPermissionsForActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get permissions for action params
func (o *GetPermissionsForActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get permissions for action params
func (o *GetPermissionsForActionParams) WithHTTPClient(client *http.Client) *GetPermissionsForActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get permissions for action params
func (o *GetPermissionsForActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get permissions for action params
func (o *GetPermissionsForActionParams) WithID(id string) *GetPermissionsForActionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get permissions for action params
func (o *GetPermissionsForActionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPermissionsForActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
