// Code generated by go-swagger; DO NOT EDIT.

package catalog_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// FindSimpleListQueryReader is a Reader for the FindSimpleListQuery structure.
type FindSimpleListQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindSimpleListQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindSimpleListQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewFindSimpleListQueryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /catalog/{namespace}/{type}] findSimpleListQuery", response, response.Code())
	}
}

// NewFindSimpleListQueryOK creates a FindSimpleListQueryOK with default headers values
func NewFindSimpleListQueryOK() *FindSimpleListQueryOK {
	return &FindSimpleListQueryOK{}
}

/*
FindSimpleListQueryOK describes a response with status code 200, with default header values.

The request is successful
*/
type FindSimpleListQueryOK struct {
	Payload *models.InventoryItems
}

// IsSuccess returns true when this find simple list query o k response has a 2xx status code
func (o *FindSimpleListQueryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find simple list query o k response has a 3xx status code
func (o *FindSimpleListQueryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find simple list query o k response has a 4xx status code
func (o *FindSimpleListQueryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find simple list query o k response has a 5xx status code
func (o *FindSimpleListQueryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find simple list query o k response a status code equal to that given
func (o *FindSimpleListQueryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find simple list query o k response
func (o *FindSimpleListQueryOK) Code() int {
	return 200
}

func (o *FindSimpleListQueryOK) Error() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{type}][%d] findSimpleListQueryOK  %+v", 200, o.Payload)
}

func (o *FindSimpleListQueryOK) String() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{type}][%d] findSimpleListQueryOK  %+v", 200, o.Payload)
}

func (o *FindSimpleListQueryOK) GetPayload() *models.InventoryItems {
	return o.Payload
}

func (o *FindSimpleListQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InventoryItems)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindSimpleListQueryUnauthorized creates a FindSimpleListQueryUnauthorized with default headers values
func NewFindSimpleListQueryUnauthorized() *FindSimpleListQueryUnauthorized {
	return &FindSimpleListQueryUnauthorized{}
}

/*
FindSimpleListQueryUnauthorized describes a response with status code 401, with default header values.

User is not authorized
*/
type FindSimpleListQueryUnauthorized struct {
}

// IsSuccess returns true when this find simple list query unauthorized response has a 2xx status code
func (o *FindSimpleListQueryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this find simple list query unauthorized response has a 3xx status code
func (o *FindSimpleListQueryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find simple list query unauthorized response has a 4xx status code
func (o *FindSimpleListQueryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this find simple list query unauthorized response has a 5xx status code
func (o *FindSimpleListQueryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this find simple list query unauthorized response a status code equal to that given
func (o *FindSimpleListQueryUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the find simple list query unauthorized response
func (o *FindSimpleListQueryUnauthorized) Code() int {
	return 401
}

func (o *FindSimpleListQueryUnauthorized) Error() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{type}][%d] findSimpleListQueryUnauthorized ", 401)
}

func (o *FindSimpleListQueryUnauthorized) String() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{type}][%d] findSimpleListQueryUnauthorized ", 401)
}

func (o *FindSimpleListQueryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
