// Code generated by go-swagger; DO NOT EDIT.

package catalog_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hmalphettes/vro-sdk-go/pkg/models"
)

// FindByRelationReader is a Reader for the FindByRelation structure.
type FindByRelationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindByRelationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindByRelationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewFindByRelationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /catalog/{namespace}/{parentType}/{parentId}/{relationName}] findByRelation", response, response.Code())
	}
}

// NewFindByRelationOK creates a FindByRelationOK with default headers values
func NewFindByRelationOK() *FindByRelationOK {
	return &FindByRelationOK{}
}

/*
FindByRelationOK describes a response with status code 200, with default header values.

The request is successful
*/
type FindByRelationOK struct {
	Payload *models.InventoryItems
}

// IsSuccess returns true when this find by relation o k response has a 2xx status code
func (o *FindByRelationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find by relation o k response has a 3xx status code
func (o *FindByRelationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find by relation o k response has a 4xx status code
func (o *FindByRelationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find by relation o k response has a 5xx status code
func (o *FindByRelationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find by relation o k response a status code equal to that given
func (o *FindByRelationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find by relation o k response
func (o *FindByRelationOK) Code() int {
	return 200
}

func (o *FindByRelationOK) Error() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{parentType}/{parentId}/{relationName}][%d] findByRelationOK  %+v", 200, o.Payload)
}

func (o *FindByRelationOK) String() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{parentType}/{parentId}/{relationName}][%d] findByRelationOK  %+v", 200, o.Payload)
}

func (o *FindByRelationOK) GetPayload() *models.InventoryItems {
	return o.Payload
}

func (o *FindByRelationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InventoryItems)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindByRelationUnauthorized creates a FindByRelationUnauthorized with default headers values
func NewFindByRelationUnauthorized() *FindByRelationUnauthorized {
	return &FindByRelationUnauthorized{}
}

/*
FindByRelationUnauthorized describes a response with status code 401, with default header values.

User is not authorized
*/
type FindByRelationUnauthorized struct {
}

// IsSuccess returns true when this find by relation unauthorized response has a 2xx status code
func (o *FindByRelationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this find by relation unauthorized response has a 3xx status code
func (o *FindByRelationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find by relation unauthorized response has a 4xx status code
func (o *FindByRelationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this find by relation unauthorized response has a 5xx status code
func (o *FindByRelationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this find by relation unauthorized response a status code equal to that given
func (o *FindByRelationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the find by relation unauthorized response
func (o *FindByRelationUnauthorized) Code() int {
	return 401
}

func (o *FindByRelationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{parentType}/{parentId}/{relationName}][%d] findByRelationUnauthorized ", 401)
}

func (o *FindByRelationUnauthorized) String() string {
	return fmt.Sprintf("[GET /catalog/{namespace}/{parentType}/{parentId}/{relationName}][%d] findByRelationUnauthorized ", 401)
}

func (o *FindByRelationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
