// Code generated by go-swagger; DO NOT EDIT.

package catalog_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewTagObjectParams creates a new TagObjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTagObjectParams() *TagObjectParams {
	return &TagObjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTagObjectParamsWithTimeout creates a new TagObjectParams object
// with the ability to set a timeout on a request.
func NewTagObjectParamsWithTimeout(timeout time.Duration) *TagObjectParams {
	return &TagObjectParams{
		timeout: timeout,
	}
}

// NewTagObjectParamsWithContext creates a new TagObjectParams object
// with the ability to set a context for a request.
func NewTagObjectParamsWithContext(ctx context.Context) *TagObjectParams {
	return &TagObjectParams{
		Context: ctx,
	}
}

// NewTagObjectParamsWithHTTPClient creates a new TagObjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewTagObjectParamsWithHTTPClient(client *http.Client) *TagObjectParams {
	return &TagObjectParams{
		HTTPClient: client,
	}
}

/*
TagObjectParams contains all the parameters to send to the API endpoint

	for the tag object operation.

	Typically these are written to a http.Request.
*/
type TagObjectParams struct {

	// Body.
	Body *models.TagInstance

	// ID.
	ID string

	// Namespace.
	Namespace string

	// Type.
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tag object params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TagObjectParams) WithDefaults() *TagObjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tag object params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TagObjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tag object params
func (o *TagObjectParams) WithTimeout(timeout time.Duration) *TagObjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tag object params
func (o *TagObjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tag object params
func (o *TagObjectParams) WithContext(ctx context.Context) *TagObjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tag object params
func (o *TagObjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tag object params
func (o *TagObjectParams) WithHTTPClient(client *http.Client) *TagObjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tag object params
func (o *TagObjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the tag object params
func (o *TagObjectParams) WithBody(body *models.TagInstance) *TagObjectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the tag object params
func (o *TagObjectParams) SetBody(body *models.TagInstance) {
	o.Body = body
}

// WithID adds the id to the tag object params
func (o *TagObjectParams) WithID(id string) *TagObjectParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the tag object params
func (o *TagObjectParams) SetID(id string) {
	o.ID = id
}

// WithNamespace adds the namespace to the tag object params
func (o *TagObjectParams) WithNamespace(namespace string) *TagObjectParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the tag object params
func (o *TagObjectParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithType adds the typeVar to the tag object params
func (o *TagObjectParams) WithType(typeVar string) *TagObjectParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the tag object params
func (o *TagObjectParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *TagObjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
