// Code generated by go-swagger; DO NOT EDIT.

package authorization_groups_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthorizationGroupParams creates a new GetAuthorizationGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthorizationGroupParams() *GetAuthorizationGroupParams {
	return &GetAuthorizationGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthorizationGroupParamsWithTimeout creates a new GetAuthorizationGroupParams object
// with the ability to set a timeout on a request.
func NewGetAuthorizationGroupParamsWithTimeout(timeout time.Duration) *GetAuthorizationGroupParams {
	return &GetAuthorizationGroupParams{
		timeout: timeout,
	}
}

// NewGetAuthorizationGroupParamsWithContext creates a new GetAuthorizationGroupParams object
// with the ability to set a context for a request.
func NewGetAuthorizationGroupParamsWithContext(ctx context.Context) *GetAuthorizationGroupParams {
	return &GetAuthorizationGroupParams{
		Context: ctx,
	}
}

// NewGetAuthorizationGroupParamsWithHTTPClient creates a new GetAuthorizationGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthorizationGroupParamsWithHTTPClient(client *http.Client) *GetAuthorizationGroupParams {
	return &GetAuthorizationGroupParams{
		HTTPClient: client,
	}
}

/*
GetAuthorizationGroupParams contains all the parameters to send to the API endpoint

	for the get authorization group operation.

	Typically these are written to a http.Request.
*/
type GetAuthorizationGroupParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get authorization group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthorizationGroupParams) WithDefaults() *GetAuthorizationGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get authorization group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthorizationGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get authorization group params
func (o *GetAuthorizationGroupParams) WithTimeout(timeout time.Duration) *GetAuthorizationGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get authorization group params
func (o *GetAuthorizationGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get authorization group params
func (o *GetAuthorizationGroupParams) WithContext(ctx context.Context) *GetAuthorizationGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get authorization group params
func (o *GetAuthorizationGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get authorization group params
func (o *GetAuthorizationGroupParams) WithHTTPClient(client *http.Client) *GetAuthorizationGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get authorization group params
func (o *GetAuthorizationGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get authorization group params
func (o *GetAuthorizationGroupParams) WithID(id string) *GetAuthorizationGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get authorization group params
func (o *GetAuthorizationGroupParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthorizationGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
