// Code generated by go-swagger; DO NOT EDIT.

package configuration_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ImportConfigurationReader is a Reader for the ImportConfiguration structure.
type ImportConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewImportConfigurationAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewImportConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewImportConfigurationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewImportConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /configurations] importConfiguration", response, response.Code())
	}
}

// NewImportConfigurationAccepted creates a ImportConfigurationAccepted with default headers values
func NewImportConfigurationAccepted() *ImportConfigurationAccepted {
	return &ImportConfigurationAccepted{}
}

/*
ImportConfigurationAccepted describes a response with status code 202, with default header values.

Configuration successfully imported
*/
type ImportConfigurationAccepted struct {
}

// IsSuccess returns true when this import configuration accepted response has a 2xx status code
func (o *ImportConfigurationAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this import configuration accepted response has a 3xx status code
func (o *ImportConfigurationAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import configuration accepted response has a 4xx status code
func (o *ImportConfigurationAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this import configuration accepted response has a 5xx status code
func (o *ImportConfigurationAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this import configuration accepted response a status code equal to that given
func (o *ImportConfigurationAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the import configuration accepted response
func (o *ImportConfigurationAccepted) Code() int {
	return 202
}

func (o *ImportConfigurationAccepted) Error() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationAccepted ", 202)
}

func (o *ImportConfigurationAccepted) String() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationAccepted ", 202)
}

func (o *ImportConfigurationAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportConfigurationBadRequest creates a ImportConfigurationBadRequest with default headers values
func NewImportConfigurationBadRequest() *ImportConfigurationBadRequest {
	return &ImportConfigurationBadRequest{}
}

/*
ImportConfigurationBadRequest describes a response with status code 400, with default header values.

Request is not valid (validation error)
*/
type ImportConfigurationBadRequest struct {
}

// IsSuccess returns true when this import configuration bad request response has a 2xx status code
func (o *ImportConfigurationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import configuration bad request response has a 3xx status code
func (o *ImportConfigurationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import configuration bad request response has a 4xx status code
func (o *ImportConfigurationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this import configuration bad request response has a 5xx status code
func (o *ImportConfigurationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this import configuration bad request response a status code equal to that given
func (o *ImportConfigurationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the import configuration bad request response
func (o *ImportConfigurationBadRequest) Code() int {
	return 400
}

func (o *ImportConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationBadRequest ", 400)
}

func (o *ImportConfigurationBadRequest) String() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationBadRequest ", 400)
}

func (o *ImportConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportConfigurationUnauthorized creates a ImportConfigurationUnauthorized with default headers values
func NewImportConfigurationUnauthorized() *ImportConfigurationUnauthorized {
	return &ImportConfigurationUnauthorized{}
}

/*
ImportConfigurationUnauthorized describes a response with status code 401, with default header values.

User is not authorized
*/
type ImportConfigurationUnauthorized struct {
}

// IsSuccess returns true when this import configuration unauthorized response has a 2xx status code
func (o *ImportConfigurationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import configuration unauthorized response has a 3xx status code
func (o *ImportConfigurationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import configuration unauthorized response has a 4xx status code
func (o *ImportConfigurationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this import configuration unauthorized response has a 5xx status code
func (o *ImportConfigurationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this import configuration unauthorized response a status code equal to that given
func (o *ImportConfigurationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the import configuration unauthorized response
func (o *ImportConfigurationUnauthorized) Code() int {
	return 401
}

func (o *ImportConfigurationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationUnauthorized ", 401)
}

func (o *ImportConfigurationUnauthorized) String() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationUnauthorized ", 401)
}

func (o *ImportConfigurationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportConfigurationNotFound creates a ImportConfigurationNotFound with default headers values
func NewImportConfigurationNotFound() *ImportConfigurationNotFound {
	return &ImportConfigurationNotFound{}
}

/*
ImportConfigurationNotFound describes a response with status code 404, with default header values.

Cannot find configuration with the specified name
*/
type ImportConfigurationNotFound struct {
}

// IsSuccess returns true when this import configuration not found response has a 2xx status code
func (o *ImportConfigurationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import configuration not found response has a 3xx status code
func (o *ImportConfigurationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import configuration not found response has a 4xx status code
func (o *ImportConfigurationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this import configuration not found response has a 5xx status code
func (o *ImportConfigurationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this import configuration not found response a status code equal to that given
func (o *ImportConfigurationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the import configuration not found response
func (o *ImportConfigurationNotFound) Code() int {
	return 404
}

func (o *ImportConfigurationNotFound) Error() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationNotFound ", 404)
}

func (o *ImportConfigurationNotFound) String() string {
	return fmt.Sprintf("[POST /configurations][%d] importConfigurationNotFound ", 404)
}

func (o *ImportConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
