// Code generated by go-swagger; DO NOT EDIT.

package policy_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPoliciesForStateParams creates a new GetPoliciesForStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPoliciesForStateParams() *GetPoliciesForStateParams {
	return &GetPoliciesForStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPoliciesForStateParamsWithTimeout creates a new GetPoliciesForStateParams object
// with the ability to set a timeout on a request.
func NewGetPoliciesForStateParamsWithTimeout(timeout time.Duration) *GetPoliciesForStateParams {
	return &GetPoliciesForStateParams{
		timeout: timeout,
	}
}

// NewGetPoliciesForStateParamsWithContext creates a new GetPoliciesForStateParams object
// with the ability to set a context for a request.
func NewGetPoliciesForStateParamsWithContext(ctx context.Context) *GetPoliciesForStateParams {
	return &GetPoliciesForStateParams{
		Context: ctx,
	}
}

// NewGetPoliciesForStateParamsWithHTTPClient creates a new GetPoliciesForStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPoliciesForStateParamsWithHTTPClient(client *http.Client) *GetPoliciesForStateParams {
	return &GetPoliciesForStateParams{
		HTTPClient: client,
	}
}

/*
GetPoliciesForStateParams contains all the parameters to send to the API endpoint

	for the get policies for state operation.

	Typically these are written to a http.Request.
*/
type GetPoliciesForStateParams struct {

	// State.
	State string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get policies for state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPoliciesForStateParams) WithDefaults() *GetPoliciesForStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get policies for state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPoliciesForStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get policies for state params
func (o *GetPoliciesForStateParams) WithTimeout(timeout time.Duration) *GetPoliciesForStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get policies for state params
func (o *GetPoliciesForStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get policies for state params
func (o *GetPoliciesForStateParams) WithContext(ctx context.Context) *GetPoliciesForStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get policies for state params
func (o *GetPoliciesForStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get policies for state params
func (o *GetPoliciesForStateParams) WithHTTPClient(client *http.Client) *GetPoliciesForStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get policies for state params
func (o *GetPoliciesForStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithState adds the state to the get policies for state params
func (o *GetPoliciesForStateParams) WithState(state string) *GetPoliciesForStateParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the get policies for state params
func (o *GetPoliciesForStateParams) SetState(state string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *GetPoliciesForStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param state
	if err := r.SetPathParam("state", o.State); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
