// Code generated by go-swagger; DO NOT EDIT.

package workflow_presentation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPresentationForParams creates a new GetPresentationForParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPresentationForParams() *GetPresentationForParams {
	return &GetPresentationForParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPresentationForParamsWithTimeout creates a new GetPresentationForParams object
// with the ability to set a timeout on a request.
func NewGetPresentationForParamsWithTimeout(timeout time.Duration) *GetPresentationForParams {
	return &GetPresentationForParams{
		timeout: timeout,
	}
}

// NewGetPresentationForParamsWithContext creates a new GetPresentationForParams object
// with the ability to set a context for a request.
func NewGetPresentationForParamsWithContext(ctx context.Context) *GetPresentationForParams {
	return &GetPresentationForParams{
		Context: ctx,
	}
}

// NewGetPresentationForParamsWithHTTPClient creates a new GetPresentationForParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPresentationForParamsWithHTTPClient(client *http.Client) *GetPresentationForParams {
	return &GetPresentationForParams{
		HTTPClient: client,
	}
}

/*
GetPresentationForParams contains all the parameters to send to the API endpoint

	for the get presentation for operation.

	Typically these are written to a http.Request.
*/
type GetPresentationForParams struct {

	// WorkflowID.
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get presentation for params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPresentationForParams) WithDefaults() *GetPresentationForParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get presentation for params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPresentationForParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get presentation for params
func (o *GetPresentationForParams) WithTimeout(timeout time.Duration) *GetPresentationForParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get presentation for params
func (o *GetPresentationForParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get presentation for params
func (o *GetPresentationForParams) WithContext(ctx context.Context) *GetPresentationForParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get presentation for params
func (o *GetPresentationForParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get presentation for params
func (o *GetPresentationForParams) WithHTTPClient(client *http.Client) *GetPresentationForParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get presentation for params
func (o *GetPresentationForParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowID adds the workflowID to the get presentation for params
func (o *GetPresentationForParams) WithWorkflowID(workflowID string) *GetPresentationForParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the get presentation for params
func (o *GetPresentationForParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPresentationForParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflowId
	if err := r.SetPathParam("workflowId", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
