// Code generated by go-swagger; DO NOT EDIT.

package service_descriptor_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServiceDescriptorsXMLSchemaParams creates a new GetServiceDescriptorsXMLSchemaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetServiceDescriptorsXMLSchemaParams() *GetServiceDescriptorsXMLSchemaParams {
	return &GetServiceDescriptorsXMLSchemaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceDescriptorsXMLSchemaParamsWithTimeout creates a new GetServiceDescriptorsXMLSchemaParams object
// with the ability to set a timeout on a request.
func NewGetServiceDescriptorsXMLSchemaParamsWithTimeout(timeout time.Duration) *GetServiceDescriptorsXMLSchemaParams {
	return &GetServiceDescriptorsXMLSchemaParams{
		timeout: timeout,
	}
}

// NewGetServiceDescriptorsXMLSchemaParamsWithContext creates a new GetServiceDescriptorsXMLSchemaParams object
// with the ability to set a context for a request.
func NewGetServiceDescriptorsXMLSchemaParamsWithContext(ctx context.Context) *GetServiceDescriptorsXMLSchemaParams {
	return &GetServiceDescriptorsXMLSchemaParams{
		Context: ctx,
	}
}

// NewGetServiceDescriptorsXMLSchemaParamsWithHTTPClient creates a new GetServiceDescriptorsXMLSchemaParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetServiceDescriptorsXMLSchemaParamsWithHTTPClient(client *http.Client) *GetServiceDescriptorsXMLSchemaParams {
	return &GetServiceDescriptorsXMLSchemaParams{
		HTTPClient: client,
	}
}

/*
GetServiceDescriptorsXMLSchemaParams contains all the parameters to send to the API endpoint

	for the get service descriptors Xml schema operation.

	Typically these are written to a http.Request.
*/
type GetServiceDescriptorsXMLSchemaParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get service descriptors Xml schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServiceDescriptorsXMLSchemaParams) WithDefaults() *GetServiceDescriptorsXMLSchemaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get service descriptors Xml schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServiceDescriptorsXMLSchemaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get service descriptors Xml schema params
func (o *GetServiceDescriptorsXMLSchemaParams) WithTimeout(timeout time.Duration) *GetServiceDescriptorsXMLSchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service descriptors Xml schema params
func (o *GetServiceDescriptorsXMLSchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service descriptors Xml schema params
func (o *GetServiceDescriptorsXMLSchemaParams) WithContext(ctx context.Context) *GetServiceDescriptorsXMLSchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service descriptors Xml schema params
func (o *GetServiceDescriptorsXMLSchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service descriptors Xml schema params
func (o *GetServiceDescriptorsXMLSchemaParams) WithHTTPClient(client *http.Client) *GetServiceDescriptorsXMLSchemaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service descriptors Xml schema params
func (o *GetServiceDescriptorsXMLSchemaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceDescriptorsXMLSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
