// Code generated by go-swagger; DO NOT EDIT.

package service_descriptor_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServiceDescriptorXMLSchemaParams creates a new GetServiceDescriptorXMLSchemaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetServiceDescriptorXMLSchemaParams() *GetServiceDescriptorXMLSchemaParams {
	return &GetServiceDescriptorXMLSchemaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceDescriptorXMLSchemaParamsWithTimeout creates a new GetServiceDescriptorXMLSchemaParams object
// with the ability to set a timeout on a request.
func NewGetServiceDescriptorXMLSchemaParamsWithTimeout(timeout time.Duration) *GetServiceDescriptorXMLSchemaParams {
	return &GetServiceDescriptorXMLSchemaParams{
		timeout: timeout,
	}
}

// NewGetServiceDescriptorXMLSchemaParamsWithContext creates a new GetServiceDescriptorXMLSchemaParams object
// with the ability to set a context for a request.
func NewGetServiceDescriptorXMLSchemaParamsWithContext(ctx context.Context) *GetServiceDescriptorXMLSchemaParams {
	return &GetServiceDescriptorXMLSchemaParams{
		Context: ctx,
	}
}

// NewGetServiceDescriptorXMLSchemaParamsWithHTTPClient creates a new GetServiceDescriptorXMLSchemaParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetServiceDescriptorXMLSchemaParamsWithHTTPClient(client *http.Client) *GetServiceDescriptorXMLSchemaParams {
	return &GetServiceDescriptorXMLSchemaParams{
		HTTPClient: client,
	}
}

/*
GetServiceDescriptorXMLSchemaParams contains all the parameters to send to the API endpoint

	for the get service descriptor Xml schema operation.

	Typically these are written to a http.Request.
*/
type GetServiceDescriptorXMLSchemaParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get service descriptor Xml schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServiceDescriptorXMLSchemaParams) WithDefaults() *GetServiceDescriptorXMLSchemaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get service descriptor Xml schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServiceDescriptorXMLSchemaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) WithTimeout(timeout time.Duration) *GetServiceDescriptorXMLSchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) WithContext(ctx context.Context) *GetServiceDescriptorXMLSchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) WithHTTPClient(client *http.Client) *GetServiceDescriptorXMLSchemaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) WithName(name string) *GetServiceDescriptorXMLSchemaParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get service descriptor Xml schema params
func (o *GetServiceDescriptorXMLSchemaParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceDescriptorXMLSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
