// Code generated by go-swagger; DO NOT EDIT.

package inventory_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new inventory service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for inventory service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	BrowseInventoryPath(params *BrowseInventoryPathParams, opts ...ClientOption) (*BrowseInventoryPathOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
BrowseInventoryPath browses inventory path

If the request is successful, the API responds with an HTTP 200 OK status code and a list containing the child objects that are located at this hierarchy level. The user can navigate hierarchy using 'up'/'down' links in the result. If there is no 'up' link, you are at the root level. If there is no 'down' link, you have reached a leaf object which is not a parent or other objects in this hierarchy. Depending on the level where you invoke the service, the results should be interpreted differently.
*/
func (a *Client) BrowseInventoryPath(params *BrowseInventoryPathParams, opts ...ClientOption) (*BrowseInventoryPathOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBrowseInventoryPathParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "browseInventoryPath",
		Method:             "GET",
		PathPattern:        "/inventory/**",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BrowseInventoryPathReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BrowseInventoryPathOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for browseInventoryPath: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
