// Code generated by go-swagger; DO NOT EDIT.

package resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPermissionsForResourceParams creates a new GetPermissionsForResourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPermissionsForResourceParams() *GetPermissionsForResourceParams {
	return &GetPermissionsForResourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPermissionsForResourceParamsWithTimeout creates a new GetPermissionsForResourceParams object
// with the ability to set a timeout on a request.
func NewGetPermissionsForResourceParamsWithTimeout(timeout time.Duration) *GetPermissionsForResourceParams {
	return &GetPermissionsForResourceParams{
		timeout: timeout,
	}
}

// NewGetPermissionsForResourceParamsWithContext creates a new GetPermissionsForResourceParams object
// with the ability to set a context for a request.
func NewGetPermissionsForResourceParamsWithContext(ctx context.Context) *GetPermissionsForResourceParams {
	return &GetPermissionsForResourceParams{
		Context: ctx,
	}
}

// NewGetPermissionsForResourceParamsWithHTTPClient creates a new GetPermissionsForResourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPermissionsForResourceParamsWithHTTPClient(client *http.Client) *GetPermissionsForResourceParams {
	return &GetPermissionsForResourceParams{
		HTTPClient: client,
	}
}

/*
GetPermissionsForResourceParams contains all the parameters to send to the API endpoint

	for the get permissions for resource operation.

	Typically these are written to a http.Request.
*/
type GetPermissionsForResourceParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get permissions for resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsForResourceParams) WithDefaults() *GetPermissionsForResourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get permissions for resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsForResourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get permissions for resource params
func (o *GetPermissionsForResourceParams) WithTimeout(timeout time.Duration) *GetPermissionsForResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get permissions for resource params
func (o *GetPermissionsForResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get permissions for resource params
func (o *GetPermissionsForResourceParams) WithContext(ctx context.Context) *GetPermissionsForResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get permissions for resource params
func (o *GetPermissionsForResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get permissions for resource params
func (o *GetPermissionsForResourceParams) WithHTTPClient(client *http.Client) *GetPermissionsForResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get permissions for resource params
func (o *GetPermissionsForResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get permissions for resource params
func (o *GetPermissionsForResourceParams) WithID(id string) *GetPermissionsForResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get permissions for resource params
func (o *GetPermissionsForResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPermissionsForResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
