// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Evaluate evaluate
//
// swagger:model evaluate
type Evaluate struct {

	// scripts
	Scripts []string `json:"scripts"`
}

// Validate validates this evaluate
func (m *Evaluate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this evaluate based on context it is used
func (m *Evaluate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Evaluate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Evaluate) UnmarshalBinary(b []byte) error {
	var res Evaluate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
