// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolicyItem policy item
//
// swagger:model policy-item
type PolicyItem struct {

	// description
	Description string `json:"description,omitempty"`

	// event source
	EventSource WsPolicyEventSource `json:"event-source,omitempty"`

	// event handlers
	EventHandlers []*EventHandler `json:"eventHandlers" xml:"event-handler"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this policy item
func (m *PolicyItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventHandlers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyItem) validateEventHandlers(formats strfmt.Registry) error {
	if swag.IsZero(m.EventHandlers) { // not required
		return nil
	}

	for i := 0; i < len(m.EventHandlers); i++ {
		if swag.IsZero(m.EventHandlers[i]) { // not required
			continue
		}

		if m.EventHandlers[i] != nil {
			if err := m.EventHandlers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("eventHandlers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("eventHandlers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this policy item based on the context it is used
func (m *PolicyItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEventHandlers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyItem) contextValidateEventHandlers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EventHandlers); i++ {

		if m.EventHandlers[i] != nil {

			if swag.IsZero(m.EventHandlers[i]) { // not required
				return nil
			}

			if err := m.EventHandlers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("eventHandlers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("eventHandlers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PolicyItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyItem) UnmarshalBinary(b []byte) error {
	var res PolicyItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
