// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Workflow workflow
//
// swagger:model workflow
type Workflow struct {

	// customized icon
	CustomizedIcon *bool `json:"customized-icon,omitempty" xml:"customized-icon,attr,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// href
	Href string `json:"href,omitempty" xml:"href,attr,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// input parameters
	InputParameters []*Parameter `json:"inputParameters" xml:"parameter"`

	// name
	Name string `json:"name,omitempty"`

	// output parameters
	OutputParameters []*Parameter `json:"outputParameters" xml:"parameter"`

	// relations
	Relations *Relations `json:"relations,omitempty"`

	// schema workflow
	SchemaWorkflow *SchemaWorkflow `json:"schema-workflow,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this workflow
func (m *Workflow) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInputParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutputParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSchemaWorkflow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Workflow) validateInputParameters(formats strfmt.Registry) error {
	if swag.IsZero(m.InputParameters) { // not required
		return nil
	}

	for i := 0; i < len(m.InputParameters); i++ {
		if swag.IsZero(m.InputParameters[i]) { // not required
			continue
		}

		if m.InputParameters[i] != nil {
			if err := m.InputParameters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inputParameters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inputParameters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workflow) validateOutputParameters(formats strfmt.Registry) error {
	if swag.IsZero(m.OutputParameters) { // not required
		return nil
	}

	for i := 0; i < len(m.OutputParameters); i++ {
		if swag.IsZero(m.OutputParameters[i]) { // not required
			continue
		}

		if m.OutputParameters[i] != nil {
			if err := m.OutputParameters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("outputParameters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("outputParameters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workflow) validateRelations(formats strfmt.Registry) error {
	if swag.IsZero(m.Relations) { // not required
		return nil
	}

	if m.Relations != nil {
		if err := m.Relations.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("relations")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("relations")
			}
			return err
		}
	}

	return nil
}

func (m *Workflow) validateSchemaWorkflow(formats strfmt.Registry) error {
	if swag.IsZero(m.SchemaWorkflow) { // not required
		return nil
	}

	if m.SchemaWorkflow != nil {
		if err := m.SchemaWorkflow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("schema-workflow")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("schema-workflow")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this workflow based on the context it is used
func (m *Workflow) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInputParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOutputParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRelations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSchemaWorkflow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Workflow) contextValidateInputParameters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InputParameters); i++ {

		if m.InputParameters[i] != nil {

			if swag.IsZero(m.InputParameters[i]) { // not required
				return nil
			}

			if err := m.InputParameters[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inputParameters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inputParameters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workflow) contextValidateOutputParameters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.OutputParameters); i++ {

		if m.OutputParameters[i] != nil {

			if swag.IsZero(m.OutputParameters[i]) { // not required
				return nil
			}

			if err := m.OutputParameters[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("outputParameters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("outputParameters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Workflow) contextValidateRelations(ctx context.Context, formats strfmt.Registry) error {

	if m.Relations != nil {

		if swag.IsZero(m.Relations) { // not required
			return nil
		}

		if err := m.Relations.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("relations")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("relations")
			}
			return err
		}
	}

	return nil
}

func (m *Workflow) contextValidateSchemaWorkflow(ctx context.Context, formats strfmt.Registry) error {

	if m.SchemaWorkflow != nil {

		if swag.IsZero(m.SchemaWorkflow) { // not required
			return nil
		}

		if err := m.SchemaWorkflow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("schema-workflow")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("schema-workflow")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Workflow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Workflow) UnmarshalBinary(b []byte) error {
	var res Workflow
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
