// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WsLog ws log
//
// swagger:model WsLog
type WsLog struct {

	// long description
	LongDescription string `json:"long-description,omitempty"`

	// severity
	// Enum: [UNKNOWN DEBUG INFO WARNING ERROR]
	Severity string `json:"severity,omitempty" xml:"severity,attr,omitempty"`

	// short description
	ShortDescription string `json:"short-description,omitempty" xml:"short-description,attr,omitempty"`

	// time stamp
	// Format: date-time
	TimeStamp strfmt.DateTime `json:"time-stamp,omitempty" xml:"time-stamp,attr,omitempty"`

	// user
	User string `json:"user,omitempty" xml:"user,attr,omitempty"`
}

// Validate validates this ws log
func (m *WsLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSeverity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeStamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var wsLogTypeSeverityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["UNKNOWN","DEBUG","INFO","WARNING","ERROR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		wsLogTypeSeverityPropEnum = append(wsLogTypeSeverityPropEnum, v)
	}
}

const (

	// WsLogSeverityUNKNOWN captures enum value "UNKNOWN"
	WsLogSeverityUNKNOWN string = "UNKNOWN"

	// WsLogSeverityDEBUG captures enum value "DEBUG"
	WsLogSeverityDEBUG string = "DEBUG"

	// WsLogSeverityINFO captures enum value "INFO"
	WsLogSeverityINFO string = "INFO"

	// WsLogSeverityWARNING captures enum value "WARNING"
	WsLogSeverityWARNING string = "WARNING"

	// WsLogSeverityERROR captures enum value "ERROR"
	WsLogSeverityERROR string = "ERROR"
)

// prop value enum
func (m *WsLog) validateSeverityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, wsLogTypeSeverityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WsLog) validateSeverity(formats strfmt.Registry) error {
	if swag.IsZero(m.Severity) { // not required
		return nil
	}

	// value enum
	if err := m.validateSeverityEnum("severity", "body", m.Severity); err != nil {
		return err
	}

	return nil
}

func (m *WsLog) validateTimeStamp(formats strfmt.Registry) error {
	if swag.IsZero(m.TimeStamp) { // not required
		return nil
	}

	if err := validate.FormatOf("time-stamp", "body", "date-time", m.TimeStamp.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this ws log based on context it is used
func (m *WsLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WsLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WsLog) UnmarshalBinary(b []byte) error {
	var res WsLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
