// Code generated by go-swagger; DO NOT EDIT.

package tagging_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTagsByTagNameAndOwnerParams creates a new GetTagsByTagNameAndOwnerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTagsByTagNameAndOwnerParams() *GetTagsByTagNameAndOwnerParams {
	return &GetTagsByTagNameAndOwnerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagsByTagNameAndOwnerParamsWithTimeout creates a new GetTagsByTagNameAndOwnerParams object
// with the ability to set a timeout on a request.
func NewGetTagsByTagNameAndOwnerParamsWithTimeout(timeout time.Duration) *GetTagsByTagNameAndOwnerParams {
	return &GetTagsByTagNameAndOwnerParams{
		timeout: timeout,
	}
}

// NewGetTagsByTagNameAndOwnerParamsWithContext creates a new GetTagsByTagNameAndOwnerParams object
// with the ability to set a context for a request.
func NewGetTagsByTagNameAndOwnerParamsWithContext(ctx context.Context) *GetTagsByTagNameAndOwnerParams {
	return &GetTagsByTagNameAndOwnerParams{
		Context: ctx,
	}
}

// NewGetTagsByTagNameAndOwnerParamsWithHTTPClient creates a new GetTagsByTagNameAndOwnerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTagsByTagNameAndOwnerParamsWithHTTPClient(client *http.Client) *GetTagsByTagNameAndOwnerParams {
	return &GetTagsByTagNameAndOwnerParams{
		HTTPClient: client,
	}
}

/*
GetTagsByTagNameAndOwnerParams contains all the parameters to send to the API endpoint

	for the get tags by tag name and owner operation.

	Typically these are written to a http.Request.
*/
type GetTagsByTagNameAndOwnerParams struct {

	// Owner.
	Owner string

	// TagName.
	TagName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tags by tag name and owner params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTagsByTagNameAndOwnerParams) WithDefaults() *GetTagsByTagNameAndOwnerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tags by tag name and owner params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTagsByTagNameAndOwnerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) WithTimeout(timeout time.Duration) *GetTagsByTagNameAndOwnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) WithContext(ctx context.Context) *GetTagsByTagNameAndOwnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) WithHTTPClient(client *http.Client) *GetTagsByTagNameAndOwnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) WithOwner(owner string) *GetTagsByTagNameAndOwnerParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithTagName adds the tagName to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) WithTagName(tagName string) *GetTagsByTagNameAndOwnerParams {
	o.SetTagName(tagName)
	return o
}

// SetTagName adds the tagName to the get tags by tag name and owner params
func (o *GetTagsByTagNameAndOwnerParams) SetTagName(tagName string) {
	o.TagName = tagName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagsByTagNameAndOwnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param tagName
	if err := r.SetPathParam("tagName", o.TagName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
