// Code generated by go-swagger; DO NOT EDIT.

package tagging_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hmalphettes/vro-sdk-go/pkg/models"
)

// ListTagOwnersReader is a Reader for the ListTagOwners structure.
type ListTagOwnersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTagOwnersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTagOwnersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListTagOwnersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tags] listTagOwners", response, response.Code())
	}
}

// NewListTagOwnersOK creates a ListTagOwnersOK with default headers values
func NewListTagOwnersOK() *ListTagOwnersOK {
	return &ListTagOwnersOK{}
}

/*
ListTagOwnersOK describes a response with status code 200, with default header values.

The request is successful
*/
type ListTagOwnersOK struct {
	Payload *models.Owners
}

// IsSuccess returns true when this list tag owners o k response has a 2xx status code
func (o *ListTagOwnersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list tag owners o k response has a 3xx status code
func (o *ListTagOwnersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list tag owners o k response has a 4xx status code
func (o *ListTagOwnersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list tag owners o k response has a 5xx status code
func (o *ListTagOwnersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list tag owners o k response a status code equal to that given
func (o *ListTagOwnersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list tag owners o k response
func (o *ListTagOwnersOK) Code() int {
	return 200
}

func (o *ListTagOwnersOK) Error() string {
	return fmt.Sprintf("[GET /tags][%d] listTagOwnersOK  %+v", 200, o.Payload)
}

func (o *ListTagOwnersOK) String() string {
	return fmt.Sprintf("[GET /tags][%d] listTagOwnersOK  %+v", 200, o.Payload)
}

func (o *ListTagOwnersOK) GetPayload() *models.Owners {
	return o.Payload
}

func (o *ListTagOwnersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Owners)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTagOwnersUnauthorized creates a ListTagOwnersUnauthorized with default headers values
func NewListTagOwnersUnauthorized() *ListTagOwnersUnauthorized {
	return &ListTagOwnersUnauthorized{}
}

/*
ListTagOwnersUnauthorized describes a response with status code 401, with default header values.

The user is not authorized
*/
type ListTagOwnersUnauthorized struct {
}

// IsSuccess returns true when this list tag owners unauthorized response has a 2xx status code
func (o *ListTagOwnersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list tag owners unauthorized response has a 3xx status code
func (o *ListTagOwnersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list tag owners unauthorized response has a 4xx status code
func (o *ListTagOwnersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list tag owners unauthorized response has a 5xx status code
func (o *ListTagOwnersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list tag owners unauthorized response a status code equal to that given
func (o *ListTagOwnersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list tag owners unauthorized response
func (o *ListTagOwnersUnauthorized) Code() int {
	return 401
}

func (o *ListTagOwnersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /tags][%d] listTagOwnersUnauthorized ", 401)
}

func (o *ListTagOwnersUnauthorized) String() string {
	return fmt.Sprintf("[GET /tags][%d] listTagOwnersUnauthorized ", 401)
}

func (o *ListTagOwnersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
