// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewDisablePluginParams creates a new DisablePluginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDisablePluginParams() *DisablePluginParams {
	return &DisablePluginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDisablePluginParamsWithTimeout creates a new DisablePluginParams object
// with the ability to set a timeout on a request.
func NewDisablePluginParamsWithTimeout(timeout time.Duration) *DisablePluginParams {
	return &DisablePluginParams{
		timeout: timeout,
	}
}

// NewDisablePluginParamsWithContext creates a new DisablePluginParams object
// with the ability to set a context for a request.
func NewDisablePluginParamsWithContext(ctx context.Context) *DisablePluginParams {
	return &DisablePluginParams{
		Context: ctx,
	}
}

// NewDisablePluginParamsWithHTTPClient creates a new DisablePluginParams object
// with the ability to set a custom HTTPClient for a request.
func NewDisablePluginParamsWithHTTPClient(client *http.Client) *DisablePluginParams {
	return &DisablePluginParams{
		HTTPClient: client,
	}
}

/*
DisablePluginParams contains all the parameters to send to the API endpoint

	for the disable plugin operation.

	Typically these are written to a http.Request.
*/
type DisablePluginParams struct {

	// Body.
	Body *models.StateContext

	// PluginName.
	PluginName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the disable plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisablePluginParams) WithDefaults() *DisablePluginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the disable plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisablePluginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the disable plugin params
func (o *DisablePluginParams) WithTimeout(timeout time.Duration) *DisablePluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable plugin params
func (o *DisablePluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable plugin params
func (o *DisablePluginParams) WithContext(ctx context.Context) *DisablePluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable plugin params
func (o *DisablePluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable plugin params
func (o *DisablePluginParams) WithHTTPClient(client *http.Client) *DisablePluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable plugin params
func (o *DisablePluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the disable plugin params
func (o *DisablePluginParams) WithBody(body *models.StateContext) *DisablePluginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the disable plugin params
func (o *DisablePluginParams) SetBody(body *models.StateContext) {
	o.Body = body
}

// WithPluginName adds the pluginName to the disable plugin params
func (o *DisablePluginParams) WithPluginName(pluginName string) *DisablePluginParams {
	o.SetPluginName(pluginName)
	return o
}

// SetPluginName adds the pluginName to the disable plugin params
func (o *DisablePluginParams) SetPluginName(pluginName string) {
	o.PluginName = pluginName
}

// WriteToRequest writes these params to a swagger request
func (o *DisablePluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param pluginName
	if err := r.SetPathParam("pluginName", o.PluginName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
